# fly.toml app configuration file generated for vc-retail-analytics
app = "vc-retail-analytics"
primary_region = "ord"

[build]

[env]
  HOST = "0.0.0.0"
  PORT = "8770"

[http_service]
  internal_port = 8770
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
