-- AQ sandbox only. Isolated from RELIEF_DEMO.
CREATE DATABASE IF NOT EXISTS VC_RETAIL_DEMO;
USE DATABASE VC_RETAIL_DEMO;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS SERVING;
CREATE WAREHOUSE IF NOT EXISTS AQ_VC_RETAIL_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
USE WAREHOUSE AQ_VC_RETAIL_WH;
ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS=60;
ALTER SESSION SET QUERY_TAG='aq-vc-retail-demo-build';
CREATE TABLE IF NOT EXISTS BRONZE.TERRITORIES(TERRITORY_ID VARCHAR, NAME VARCHAR, REGION VARCHAR, CAPACITY_DEALERS NUMBER);
CREATE TABLE IF NOT EXISTS BRONZE.SALESPEOPLE(REP_ID VARCHAR, NAME VARCHAR, TERRITORY_ID VARCHAR, HIRE_MONTH VARCHAR, QUARTERLY_QUOTA_CENTS NUMBER);
CREATE TABLE IF NOT EXISTS BRONZE.VENDORS(VENDOR_ID VARCHAR, NAME VARCHAR, COUNTRY VARCHAR);
CREATE TABLE IF NOT EXISTS BRONZE.DEALERS(DEALER_ID VARCHAR, NAME VARCHAR, REGION VARCHAR, CHANNEL_FOCUS VARCHAR, CITY VARCHAR, TERRITORY_ID VARCHAR);
CREATE TABLE IF NOT EXISTS BRONZE.PRODUCTS(
  SKU_ID VARCHAR, NAME VARCHAR, FAMILY VARCHAR, DESIGNER VARCHAR, FINISH VARCHAR,
  LIST_PRICE_CENTS NUMBER, LEAD_BAND VARCHAR, COST_CENTS NUMBER, VENDOR_ID VARCHAR, SAFETY_STOCK NUMBER
);
CREATE TABLE IF NOT EXISTS BRONZE.EVENTS(EVENT_ID VARCHAR,DEALER_ID VARCHAR,SOURCE_ID VARCHAR,VERSION NUMBER,OP VARCHAR,PAYLOAD VARIANT,RECEIVED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS BRONZE.MONTHLY_FACTS(
  DEALER_ID VARCHAR, SKU_ID VARCHAR, MONTH VARCHAR, UNITS_SOLD NUMBER,
  NET_SALES_CENTS NUMBER, MARGIN_CENTS NUMBER, FAMILY VARCHAR, CHANNEL VARCHAR, REGION VARCHAR, REP_ID VARCHAR
);
CREATE TABLE IF NOT EXISTS BRONZE.VENDOR_KPI(
  VENDOR_ID VARCHAR, OTIF_PCT FLOAT, DEFECT_PCT FLOAT, AVG_LEAD_DAYS FLOAT, PROMISED_LEAD_DAYS FLOAT, SHIPMENTS NUMBER
);
CREATE STAGE IF NOT EXISTS BRONZE.INGEST_STAGE FILE_FORMAT=(TYPE=JSON);
CREATE TABLE IF NOT EXISTS BRONZE.INCOMING(V VARIANT);
