USE DATABASE VC_RETAIL_DEMO;
USE WAREHOUSE AQ_VC_RETAIL_WH;
-- Event-sourced path (small, versioned, quarantined). 08_silver_gold.sql later rebuilds the SILVER tables
-- from the TPC-DS backbone UNION these event facts; the views below stay as the event lineage.
CREATE OR REPLACE VIEW SILVER.NORMALIZED AS
SELECT e.*,
  PAYLOAD:sku_id::VARCHAR AS PAYLOAD_SKU,
  PAYLOAD:channel::VARCHAR AS CHANNEL,
  PAYLOAD:family::VARCHAR AS FAMILY,
  PAYLOAD:region::VARCHAR AS REGION,
  TRY_TO_NUMBER(PAYLOAD:units_sold::VARCHAR) AS UNITS_SOLD,
  TRY_TO_NUMBER(PAYLOAD:net_sales_cents::VARCHAR) AS NET_SALES_CENTS,
  TRY_TO_NUMBER(PAYLOAD:margin_cents::VARCHAR) AS MARGIN_CENTS,
  TRY_TO_NUMBER(PAYLOAD:on_hand::VARCHAR) AS ON_HAND,
  PAYLOAD:lead_band::VARCHAR AS LEAD_BAND,
  PAYLOAD:rep_id::VARCHAR AS REP_ID,
  TRY_TO_NUMBER(PAYLOAD:cost_cents::VARCHAR) AS COST_CENTS,
  CASE
    WHEN d.DEALER_ID IS NULL THEN 'unknown_dealer'
    WHEN OP NOT IN ('upsert','delete') OR VERSION IS NULL OR VERSION<1 THEN 'invalid_envelope'
    WHEN OP='delete' THEN NULL
    WHEN PAYLOAD:sku_id IS NULL OR PAYLOAD:channel IS NULL OR PAYLOAD:family IS NULL OR PAYLOAD:currency IS NULL OR PAYLOAD:amount_unit IS NULL OR PAYLOAD:rep_id IS NULL OR PAYLOAD:cost_cents IS NULL THEN 'missing_field'
    WHEN PAYLOAD:sku_id::VARCHAR<>SOURCE_ID THEN 'identity_mismatch'
    WHEN PAYLOAD:currency::VARCHAR<>'USD' OR PAYLOAD:amount_unit::VARCHAR<>'cents' THEN 'unsupported_currency_or_unit'
    WHEN CHANNEL NOT IN ('Consumer','Trade','Contract') THEN 'unknown_channel'
    WHEN FAMILY NOT IN ('Ceiling','Wall','Lamps','Outdoor','Fans','Alabaster','Cordless') THEN 'unknown_family'
    WHEN UNITS_SOLD IS NULL OR NET_SALES_CENTS IS NULL OR MARGIN_CENTS IS NULL OR ON_HAND IS NULL OR COST_CENTS IS NULL OR UNITS_SOLD<0 OR NET_SALES_CENTS<0 OR MARGIN_CENTS<0 OR ON_HAND<0 OR COST_CENTS<0 THEN 'invalid_amount'
    WHEN MARGIN_CENTS>NET_SALES_CENTS THEN 'margin_exceeds_sales'
    WHEN LEAD_BAND NOT IN ('in_stock','2_4_weeks','4_8_weeks','custom_overseas') THEN 'unknown_lead_band'
  END AS REASON
FROM BRONZE.EVENTS e
LEFT JOIN BRONZE.DEALERS d ON e.DEALER_ID=d.DEALER_ID;
CREATE OR REPLACE VIEW SILVER.LATEST AS
SELECT * FROM SILVER.NORMALIZED QUALIFY ROW_NUMBER() OVER(PARTITION BY DEALER_ID,SOURCE_ID ORDER BY VERSION DESC,RECEIVED_AT DESC,EVENT_ID DESC)=1;
CREATE OR REPLACE VIEW SILVER.FACTS_EVENTS AS
SELECT DEALER_ID,SOURCE_ID AS SKU_ID,VERSION,CHANNEL,FAMILY,COALESCE(d.REGION, REGION) AS REGION,
  UNITS_SOLD,NET_SALES_CENTS,MARGIN_CENTS,ON_HAND,LEAD_BAND,REP_ID,COST_CENTS
FROM SILVER.LATEST l
LEFT JOIN BRONZE.DEALERS d USING (DEALER_ID)
WHERE REASON IS NULL AND OP='upsert';
CREATE OR REPLACE VIEW SILVER.QUARANTINE_EVENTS AS
SELECT EVENT_ID,DEALER_ID,SOURCE_ID,REASON FROM SILVER.NORMALIZED WHERE REASON IS NOT NULL;
-- Silver tables: initial fill from events; 08 replaces with backbone + events.
CREATE TABLE IF NOT EXISTS SILVER.FACTS AS SELECT * FROM SILVER.FACTS_EVENTS;
CREATE TABLE IF NOT EXISTS SILVER.QUARANTINE AS SELECT * FROM SILVER.QUARANTINE_EVENTS;
CREATE TABLE IF NOT EXISTS SILVER.MONTHLY AS SELECT * FROM BRONZE.MONTHLY_FACTS;
CREATE TABLE IF NOT EXISTS SILVER.VENDOR_KPI AS SELECT * FROM BRONZE.VENDOR_KPI;
CREATE TABLE IF NOT EXISTS GOLD.CHANNEL_FAMILY AS
SELECT DEALER_ID,CHANNEL,REGION,FAMILY,
  SUM(UNITS_SOLD) AS UNITS_SOLD,
  SUM(NET_SALES_CENTS)/100.0 AS NET_SALES,
  SUM(MARGIN_CENTS)/100.0 AS MARGIN,
  SUM(ON_HAND) AS ON_HAND
FROM SILVER.FACTS GROUP BY DEALER_ID,CHANNEL,REGION,FAMILY;
CREATE OR REPLACE SECURE VIEW SERVING.SILVER_FACTS AS SELECT * FROM SILVER.FACTS;
CREATE OR REPLACE SECURE VIEW SERVING.SILVER_MONTHLY AS SELECT * FROM SILVER.MONTHLY;
CREATE OR REPLACE SECURE VIEW SERVING.SILVER_VENDOR_KPI AS SELECT * FROM SILVER.VENDOR_KPI;
CREATE OR REPLACE SECURE VIEW SERVING.DEALERS AS SELECT * FROM BRONZE.DEALERS;
CREATE OR REPLACE SECURE VIEW SERVING.PRODUCTS AS SELECT * FROM BRONZE.PRODUCTS;
CREATE OR REPLACE SECURE VIEW SERVING.TERRITORIES AS SELECT * FROM BRONZE.TERRITORIES;
CREATE OR REPLACE SECURE VIEW SERVING.SALESPEOPLE AS SELECT * FROM BRONZE.SALESPEOPLE;
CREATE OR REPLACE SECURE VIEW SERVING.VENDORS AS SELECT * FROM BRONZE.VENDORS;
CREATE OR REPLACE SECURE VIEW SERVING.QUARANTINE AS SELECT * FROM SILVER.QUARANTINE;
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_CHANNEL_FAMILY AS SELECT * FROM GOLD.CHANNEL_FAMILY;
CREATE OR REPLACE VIEW SERVING.RUNS AS SELECT NULL::VARCHAR RUN_ID,NULL::VARCHAR FINISHED_AT,0::NUMBER ACCEPTED,0::NUMBER DUPLICATES,0::NUMBER QUARANTINED,0::NUMBER CURRENT_FACTS,0::FLOAT DURATION_MS WHERE FALSE;
