USE DATABASE VC_RETAIL_DEMO;
CREATE ROLE IF NOT EXISTS AQ_VC_READER;
CREATE TABLE IF NOT EXISTS GOVERNANCE.USER_DEALERS(USER_NAME VARCHAR,DEALER_ID VARCHAR);
CREATE ROW ACCESS POLICY IF NOT EXISTS GOVERNANCE.DEALER_SCOPE AS (DID VARCHAR) RETURNS BOOLEAN ->
 EXISTS(SELECT 1 FROM VC_RETAIL_DEMO.GOVERNANCE.USER_DEALERS p WHERE p.USER_NAME=CURRENT_USER() AND (p.DEALER_ID=DID OR p.DEALER_ID='*'));
-- Dealer-keyed serving views. Re-run after 08 (CREATE OR REPLACE VIEW drops policies); cloud.py tolerates "already attached".
ALTER VIEW SERVING.SILVER_FACTS ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
ALTER VIEW SERVING.SILVER_MONTHLY ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
ALTER VIEW SERVING.DEALERS ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
ALTER VIEW SERVING.QUARANTINE ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
ALTER VIEW SERVING.GOLD_CHANNEL_FAMILY ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
ALTER VIEW SERVING.GOLD_CHANNEL_FAMILY_ALL ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
ALTER VIEW SERVING.REP_ASSIGNMENTS ADD ROW ACCESS POLICY GOVERNANCE.DEALER_SCOPE ON(DEALER_ID);
-- Corporate supply-chain views (POs, inventory, MRP, BOM, vendors) are not dealer-keyed; they are visible to any reader
-- with the role. Documented in docs/KNOWN_LIMITATIONS.md.
GRANT USAGE ON WAREHOUSE AQ_VC_RETAIL_WH TO ROLE AQ_VC_READER;
GRANT USAGE ON DATABASE VC_RETAIL_DEMO TO ROLE AQ_VC_READER;
GRANT USAGE ON SCHEMA SERVING TO ROLE AQ_VC_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SERVING TO ROLE AQ_VC_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SERVING TO ROLE AQ_VC_READER;
-- Insert exact CURRENT_USER() into USER_DEALERS (DLR-0001 or '*'). PRODUCTS has no dealer key — grant is view-level only.
