USE DATABASE VC_RETAIL_DEMO;
USE WAREHOUSE AQ_VC_RETAIL_WH;
SELECT 'silver_facts' AS k, COUNT(*) AS n FROM SILVER.FACTS
UNION ALL SELECT 'gold_rows', COUNT(*) FROM GOLD.CHANNEL_FAMILY
UNION ALL SELECT 'dealers', COUNT(*) FROM BRONZE.DEALERS
UNION ALL SELECT 'products', COUNT(*) FROM BRONZE.PRODUCTS
UNION ALL SELECT 'quarantine', COUNT(*) FROM SILVER.QUARANTINE;
SELECT CHANNEL, SUM(NET_SALES) AS NET_SALES FROM GOLD.CHANNEL_FAMILY GROUP BY CHANNEL ORDER BY NET_SALES DESC;
