USE DATABASE VC_RETAIL_DEMO;
USE WAREHOUSE AQ_VC_RETAIL_WH;
-- Row counts per layer
SELECT 'silver_facts' AS k, COUNT(*) AS n FROM SILVER.FACTS
UNION ALL SELECT 'silver_monthly', COUNT(*) FROM SILVER.MONTHLY
UNION ALL SELECT 'gold_channel_family', COUNT(*) FROM GOLD.CHANNEL_FAMILY
UNION ALL SELECT 'gold_channel_family_all', COUNT(*) FROM GOLD.CHANNEL_FAMILY_ALL
UNION ALL SELECT 'dealers', COUNT(*) FROM BRONZE.DEALERS
UNION ALL SELECT 'products', COUNT(*) FROM BRONZE.PRODUCTS
UNION ALL SELECT 'salespeople', COUNT(*) FROM BRONZE.SALESPEOPLE
UNION ALL SELECT 'vendors', COUNT(*) FROM BRONZE.VENDORS
UNION ALL SELECT 'purchase_orders', COUNT(*) FROM BRONZE.PURCHASE_ORDERS
UNION ALL SELECT 'po_lines', COUNT(*) FROM BRONZE.PO_LINES
UNION ALL SELECT 'shipments', COUNT(*) FROM BRONZE.SHIPMENTS
UNION ALL SELECT 'receipts', COUNT(*) FROM BRONZE.RECEIPTS
UNION ALL SELECT 'inventory_snapshots', COUNT(*) FROM BRONZE.INVENTORY_SNAPSHOTS
UNION ALL SELECT 'demand_forecast', COUNT(*) FROM BRONZE.DEMAND_FORECAST
UNION ALL SELECT 'mrp_plan', COUNT(*) FROM BRONZE.MRP_PLAN
UNION ALL SELECT 'bom', COUNT(*) FROM BRONZE.BOM
UNION ALL SELECT 'quarantine', COUNT(*) FROM SILVER.QUARANTINE;
-- Channel totals
SELECT CHANNEL, SUM(NET_SALES) AS NET_SALES FROM GOLD.CHANNEL_FAMILY_ALL GROUP BY CHANNEL ORDER BY NET_SALES DESC;
-- Backbone size evidence (shared TPC-DS SF10TCL) and our materialized footprint
SELECT 'tpcds_sf10tcl_backbone' AS layer, ROUND(SUM(BYTES)/POWER(1024,4), 2) AS tb, SUM(ROW_COUNT) AS row_cnt
FROM SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='TPCDS_SF10TCL'
UNION ALL
SELECT 'vc_retail_demo_' || TABLE_SCHEMA, ROUND(SUM(BYTES)/POWER(1024,4), 4), SUM(ROW_COUNT)
FROM VC_RETAIL_DEMO.INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' GROUP BY TABLE_SCHEMA;
-- Quarantine reasons (scoped dealers)
SELECT REASON, COUNT(*) AS N FROM SILVER.QUARANTINE GROUP BY REASON ORDER BY N DESC;
-- Integrity checks (all should be 0)
SELECT 'po_lines_without_po' AS chk, COUNT(*) AS n FROM BRONZE.PO_LINES pl LEFT JOIN BRONZE.PURCHASE_ORDERS po ON po.PO_ID=pl.PO_ID WHERE po.PO_ID IS NULL
UNION ALL SELECT 'facts_unknown_dealer', COUNT(*) FROM SILVER.FACTS f LEFT JOIN BRONZE.DEALERS d ON d.DEALER_ID=f.DEALER_ID WHERE d.DEALER_ID IS NULL
UNION ALL SELECT 'facts_margin_gt_sales', COUNT(*) FROM SILVER.FACTS WHERE MARGIN_CENTS > NET_SALES_CENTS
UNION ALL SELECT 'dealers_without_active_rep', COUNT(*) FROM BRONZE.DEALERS d LEFT JOIN SILVER.DEALER_REP r ON r.DEALER_ID=d.DEALER_ID WHERE r.REP_ID IS NULL;
