-- Silver + Gold rebuild from the 10 TB backbone (06) and the generated layer (07), unioned with the
-- event-sourced facts (02). Two heavy passes over the TPC-DS sales tables; everything else is small.
--   Pass 1: scoped-dealer raw extract  -> SILVER.FACTS (dealer x SKU), SILVER.QUARANTINE (invalid source rows)
--   Pass 2: grouping-sets aggregate    -> GOLD.MONTHLY_BASE (all dealers), SILVER.ITEM_MONTHLY (forecast actuals)
USE DATABASE VC_RETAIL_DEMO;
USE WAREHOUSE {{BUILD_WH}};
ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS={{BUILD_TIMEOUT}};
ALTER SESSION SET QUERY_TAG='aq-vc-retail-silver-gold';

-- Demo scope: dealer x SKU grain is kept for the first {{DEMO_DEALER_COUNT}} dealers (DLR-0001..); Gold spans all 1,500.
CREATE OR REPLACE TABLE SILVER.DEMO_DEALERS AS
SELECT DEALER_ID FROM BRONZE.DEALERS ORDER BY DEALER_ID LIMIT {{DEMO_DEALER_COUNT}};

-- ---------------------------------------------------------------- pass 1: scoped raw extract
CREATE OR REPLACE TABLE SILVER.BACKBONE_SCOPED CLUSTER BY (DEALER_ID) AS
SELECT s.CHANNEL, s.DEALER_ID, s.ITEM_SK, s.MONTH, s.CAL_DATE, s.QTY, s.NET_PAID, s.DISC_RATIO, s.DOC_NO
FROM BRONZE.BACKBONE_SALES s
WHERE s.DEALER_ID IN (SELECT DEALER_ID FROM SILVER.DEMO_DEALERS);

-- Validation reasons mirror the event path (invalid_amount / unknown_sku / margin rules applied after re-skin).
-- Net = re-skinned list price x row discount x qty (TPC-DS dollar columns are not used for money).
CREATE OR REPLACE TABLE SILVER.BACKBONE_SCOPED_VALIDATED CLUSTER BY (DEALER_ID) AS
SELECT b.*, p.SKU_ID, p.FAMILY, p.LEAD_BAND, p.COST_CENTS, p.LIST_PRICE_CENTS,
       ROUND(b.QTY * p.LIST_PRICE_CENTS * b.DISC_RATIO)::NUMBER AS NET_SALES_CENTS,
       CASE
         WHEN p.SKU_ID IS NULL THEN 'unknown_sku'
         WHEN b.QTY IS NULL OR b.NET_PAID IS NULL THEN 'missing_field'
         WHEN b.QTY <= 0 OR b.NET_PAID < 0 THEN 'invalid_amount'
       END AS REASON
FROM SILVER.BACKBONE_SCOPED b
LEFT JOIN BRONZE.PRODUCTS_BACKBONE p ON p.ITEM_SK = b.ITEM_SK;

-- Current rep per dealer (active assignment).
CREATE OR REPLACE TABLE SILVER.DEALER_REP AS
SELECT DEALER_ID, REP_ID FROM BRONZE.REP_ASSIGNMENTS WHERE END_MONTH IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY DEALER_ID ORDER BY START_MONTH DESC, REP_ID) = 1;

-- Dealer showroom stock: DC stock is corporate (BRONZE.INVENTORY_SNAPSHOTS), so dealer on-hand is derived from the
-- dealer's own trailing demand: ~15% of dealer x SKU rows are stocked out, the rest hold 1-6 months of average demand
-- (at least one display unit). Deterministic per (dealer, SKU).
CREATE OR REPLACE TABLE SILVER.DEALER_ON_HAND CLUSTER BY (DEALER_ID) AS
SELECT v.DEALER_ID, v.SKU_ID,
       IFF(MOD(ABS(HASH(v.DEALER_ID, v.SKU_ID)), 100) < 15, 0,
           GREATEST(1, CEIL(SUM(v.QTY) / 12.0 * (1 + MOD(ABS(HASH(v.SKU_ID, v.DEALER_ID)), 6)))))::NUMBER AS ON_HAND
FROM SILVER.BACKBONE_SCOPED_VALIDATED v
WHERE v.REASON IS NULL AND v.MONTH >= TO_VARCHAR(DATEADD(month, -11, '{{AS_OF}}'::DATE), 'YYYY-MM')
GROUP BY v.DEALER_ID, v.SKU_ID;

-- SILVER.FACTS: trailing-12-month dealer x SKU facts for the demo scope, UNION event-sourced facts (02).
-- Window = the 12 calendar months ending in AS_OF's month (-11 months, not -12, which would be 13 months).
CREATE OR REPLACE TABLE SILVER.FACTS CLUSTER BY (DEALER_ID) AS
WITH agg AS (
  SELECT v.DEALER_ID, v.SKU_ID, v.FAMILY, v.LEAD_BAND, v.COST_CENTS,
         -- channel = the dominant channel for this dealer x SKU
         MODE(v.CHANNEL) AS CHANNEL,
         SUM(v.QTY) AS UNITS_SOLD, SUM(v.NET_SALES_CENTS) AS NET_SALES_CENTS
  FROM SILVER.BACKBONE_SCOPED_VALIDATED v
  WHERE v.REASON IS NULL AND v.MONTH >= TO_VARCHAR(DATEADD(month, -11, '{{AS_OF}}'::DATE), 'YYYY-MM')
  GROUP BY v.DEALER_ID, v.SKU_ID, v.FAMILY, v.LEAD_BAND, v.COST_CENTS
)
SELECT a.DEALER_ID, a.SKU_ID, 1 AS VERSION, a.CHANNEL, a.FAMILY, d.REGION,
       a.UNITS_SOLD, a.NET_SALES_CENTS,
       -- margin = net - cost, floored at 0 and capped at 55% of net (same rule as the synthetic seed)
       LEAST(ROUND(a.NET_SALES_CENTS * 0.55), GREATEST(0, a.NET_SALES_CENTS - a.COST_CENTS * a.UNITS_SOLD))::NUMBER AS MARGIN_CENTS,
       COALESCE(oh.ON_HAND, 0) AS ON_HAND, a.LEAD_BAND, COALESCE(r.REP_ID, 'REP-UNASSIGNED') AS REP_ID, a.COST_CENTS
FROM agg a
JOIN BRONZE.DEALERS d ON d.DEALER_ID = a.DEALER_ID
LEFT JOIN SILVER.DEALER_ON_HAND oh ON oh.DEALER_ID = a.DEALER_ID AND oh.SKU_ID = a.SKU_ID
LEFT JOIN SILVER.DEALER_REP r ON r.DEALER_ID = a.DEALER_ID
UNION ALL
SELECT DEALER_ID, SKU_ID, VERSION, CHANNEL, FAMILY, REGION, UNITS_SOLD, NET_SALES_CENTS, MARGIN_CENTS, ON_HAND, LEAD_BAND, REP_ID, COST_CENTS
FROM SILVER.FACTS_EVENTS;

-- SILVER.QUARANTINE: event quarantine UNION invalid backbone source rows (one row per source document line).
CREATE OR REPLACE TABLE SILVER.QUARANTINE CLUSTER BY (DEALER_ID) AS
SELECT EVENT_ID, DEALER_ID, SOURCE_ID, REASON FROM SILVER.QUARANTINE_EVENTS
UNION ALL
SELECT 'BB-' || CHANNEL || '-' || DOC_NO || '-' || ITEM_SK AS EVENT_ID, DEALER_ID,
       COALESCE(SKU_ID, 'SKU-' || LPAD(ITEM_SK, 6, '0')) AS SOURCE_ID, REASON
FROM SILVER.BACKBONE_SCOPED_VALIDATED WHERE REASON IS NOT NULL;

-- ---------------------------------------------------------------- pass 2: all-dealer aggregates (one scan, grouping sets)
CREATE OR REPLACE TABLE GOLD.SALES_GROUPING_SETS AS
SELECT GROUPING_ID(s.DEALER_ID, p.FAMILY, s.CHANNEL, p.ITEM_SK) AS GID,
       s.DEALER_ID, p.FAMILY, s.CHANNEL, p.ITEM_SK, s.MONTH,
       SUM(s.QTY) AS UNITS_SOLD,
       SUM(ROUND(s.QTY * p.LIST_PRICE_CENTS * s.DISC_RATIO)) AS NET_SALES_CENTS,
       SUM(LEAST(ROUND(s.QTY * p.LIST_PRICE_CENTS * s.DISC_RATIO * 0.55),
                 GREATEST(0, ROUND(s.QTY * p.LIST_PRICE_CENTS * s.DISC_RATIO) - p.COST_CENTS * s.QTY))) AS MARGIN_CENTS
FROM BRONZE.BACKBONE_SALES s
JOIN BRONZE.PRODUCTS_BACKBONE p ON p.ITEM_SK = s.ITEM_SK
WHERE s.DEALER_ID IS NOT NULL AND s.QTY > 0 AND s.NET_PAID >= 0
GROUP BY GROUPING SETS ((s.DEALER_ID, p.FAMILY, s.CHANNEL, s.MONTH), (p.ITEM_SK, s.MONTH));

CREATE OR REPLACE TABLE GOLD.MONTHLY_BASE CLUSTER BY (MONTH) AS
SELECT g.DEALER_ID, g.FAMILY, g.CHANNEL, g.MONTH, d.REGION, g.UNITS_SOLD, g.NET_SALES_CENTS, g.MARGIN_CENTS
FROM GOLD.SALES_GROUPING_SETS g JOIN BRONZE.DEALERS d ON d.DEALER_ID = g.DEALER_ID
WHERE g.ITEM_SK IS NULL AND g.DEALER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.ITEM_MONTHLY CLUSTER BY (MONTH) AS
SELECT 'SKU-' || LPAD(g.ITEM_SK, 6, '0') AS SKU_ID, g.MONTH, g.UNITS_SOLD
FROM GOLD.SALES_GROUPING_SETS g WHERE g.ITEM_SK IS NOT NULL AND g.DEALER_ID IS NULL;

-- SILVER.MONTHLY: dealer x family x channel x month (all dealers) with the rep as-of that month. SKU_ID is NULL at this grain.
CREATE OR REPLACE TABLE SILVER.MONTHLY CLUSTER BY (MONTH) AS
SELECT m.DEALER_ID, NULL::VARCHAR AS SKU_ID, m.MONTH, m.UNITS_SOLD, m.NET_SALES_CENTS, m.MARGIN_CENTS,
       m.FAMILY, m.CHANNEL, m.REGION, COALESCE(ra.REP_ID, 'REP-UNASSIGNED') AS REP_ID
FROM GOLD.MONTHLY_BASE m
LEFT JOIN BRONZE.REP_ASSIGNMENTS ra ON ra.DEALER_ID = m.DEALER_ID AND ra.START_MONTH <= m.MONTH AND (ra.END_MONTH IS NULL OR ra.END_MONTH >= m.MONTH)
QUALIFY ROW_NUMBER() OVER (PARTITION BY m.DEALER_ID, m.FAMILY, m.CHANNEL, m.MONTH ORDER BY ra.START_MONTH DESC NULLS LAST) = 1;

-- ---------------------------------------------------------------- sales org (depends on actuals)
CREATE OR REPLACE TABLE BRONZE.REP_QUOTAS AS
WITH q AS (
  SELECT REP_ID, SUBSTR(MONTH,1,4) || CASE WHEN SUBSTR(MONTH,6,2) IN ('01','02','03') THEN '-Q1' WHEN SUBSTR(MONTH,6,2) IN ('04','05','06') THEN '-Q2'
                                            WHEN SUBSTR(MONTH,6,2) IN ('07','08','09') THEN '-Q3' ELSE '-Q4' END AS QUARTER,
         SUM(NET_SALES_CENTS) AS Q_CENTS
  FROM SILVER.MONTHLY GROUP BY REP_ID, QUARTER
  -- full quarters only (the calendar window may spill a day into a neighbouring quarter)
  HAVING COUNT(DISTINCT MONTH) = 3
), recent AS (SELECT DISTINCT QUARTER FROM q ORDER BY QUARTER DESC LIMIT 4),
   -- quota base = the rep's trailing-4-quarter average (a rep's book of dealers changes over the window)
   base AS (SELECT REP_ID, AVG(Q_CENTS) AS AVG_Q FROM q WHERE QUARTER IN (SELECT QUARTER FROM recent) GROUP BY REP_ID),
   -- company seasonal index: TPC-DS has strong Q4 / Q3 peaks; quotas follow the same seasonality so attainment
   -- centres near 100% and the spread is rep-level over/under-performance, not the calendar.
   season AS (SELECT QUARTER, SUM(Q_CENTS) / (SELECT SUM(Q_CENTS) / COUNT(DISTINCT QUARTER) FROM q) AS IDX FROM q GROUP BY QUARTER),
   idx AS (SELECT QUARTER, IDX, ROW_NUMBER() OVER (ORDER BY QUARTER) - 1 AS I FROM season)
SELECT sp.REP_ID, idx.QUARTER,
       ROUND(COALESCE(b.AVG_Q, sp.QUARTERLY_QUOTA_CENTS) * idx.IDX
             * (0.85 + UNIFORM(0::FLOAT, 1::FLOAT, RANDOM(91)) * 0.30)
             -- annual growth trend (public: headcount +26% over 2023-26), centred on the trailing-4-quarter midpoint so
             -- the quota base and the growth factor agree on the recent quarters
             * POWER({{GROWTH}}, (idx.I - 5.5) / 4.0))::NUMBER AS QUOTA_CENTS
FROM BRONZE.SALESPEOPLE sp CROSS JOIN idx LEFT JOIN base b ON b.REP_ID = sp.REP_ID;

-- ---------------------------------------------------------------- vendor KPI from receipts (replaces loaded synthetic KPI)
CREATE OR REPLACE TABLE SILVER.VENDOR_KPI AS
WITH line_agg AS (SELECT PO_ID, SUM(QTY_ORDERED) AS ORDERED, SUM(QTY_RECEIVED) AS RECEIVED FROM BRONZE.PO_LINES GROUP BY PO_ID),
     ship_agg AS (SELECT PO_ID, MAX(ARRIVAL_DATE) AS ARRIVAL, COUNT(*) AS SHIPS FROM BRONZE.SHIPMENTS WHERE ARRIVAL_DATE IS NOT NULL GROUP BY PO_ID),
     perf AS (
       SELECT po.VENDOR_ID, po.PO_ID, IFF(s.ARRIVAL <= po.PROMISED_DATE, 1, 0) AS ON_TIME, IFF(l.RECEIVED >= l.ORDERED, 1, 0) AS IN_FULL,
              DATEDIFF(day, po.ORDER_DATE, s.ARRIVAL) AS ACTUAL_LEAD, po.LEAD_DAYS AS PROMISED_LEAD, s.SHIPS
       FROM BRONZE.PURCHASE_ORDERS po JOIN line_agg l ON l.PO_ID = po.PO_ID JOIN ship_agg s ON s.PO_ID = po.PO_ID
       WHERE po.STATUS IN ('received','closed')
     ),
     defects AS (SELECT po.VENDOR_ID, SUM(r.QTY_DEFECTIVE) AS DEF, SUM(r.QTY_RECEIVED) AS RCV FROM BRONZE.RECEIPTS r JOIN BRONZE.PURCHASE_ORDERS po ON po.PO_ID = r.PO_ID GROUP BY po.VENDOR_ID)
SELECT p.VENDOR_ID,
       ROUND(100.0 * SUM(p.ON_TIME * p.IN_FULL) / NULLIF(COUNT(*), 0), 1) AS OTIF_PCT,
       ROUND(100.0 * COALESCE(MAX(d.DEF), 0) / NULLIF(MAX(d.RCV), 0), 2) AS DEFECT_PCT,
       ROUND(AVG(p.ACTUAL_LEAD), 1) AS AVG_LEAD_DAYS,
       ROUND(AVG(p.PROMISED_LEAD), 1) AS PROMISED_LEAD_DAYS,
       SUM(p.SHIPS) AS SHIPMENTS
FROM perf p LEFT JOIN defects d ON d.VENDOR_ID = p.VENDOR_ID
GROUP BY p.VENDOR_ID;

-- ---------------------------------------------------------------- inventory snapshots (backbone weekly + on-order / allocated / in-transit)
CREATE OR REPLACE TABLE BRONZE.INVENTORY_SNAPSHOTS CLUSTER BY (SNAPSHOT_WEEK, DC_ID) AS
WITH latest AS (SELECT MAX(SNAPSHOT_WEEK) AS W FROM BRONZE.INVENTORY_BACKBONE),
     dcw AS (SELECT DC_ID, WEIGHT / SUM(WEIGHT) OVER () AS W FROM BRONZE.DISTRIBUTION_CENTERS),
     on_order AS (
       SELECT pl.SKU_ID, SUM(pl.QTY_ORDERED - pl.QTY_RECEIVED) AS OPEN_QTY,
              SUM(IFF(po.STATUS = 'in_transit', pl.QTY_ORDERED - pl.QTY_RECEIVED, 0)) AS TRANSIT_QTY
       FROM BRONZE.PO_LINES pl JOIN BRONZE.PURCHASE_ORDERS po ON po.PO_ID = pl.PO_ID
       WHERE po.STATUS IN ('open','in_transit') GROUP BY pl.SKU_ID
     )
SELECT i.SNAPSHOT_WEEK, i.DC_ID, i.SKU_ID, i.ON_HAND,
       -- open / in-transit PO quantity is allocated to DCs by DC weight (Houston carries the largest share)
       IFF(i.SNAPSHOT_WEEK = latest.W, ROUND(COALESCE(o.OPEN_QTY, 0) * dcw.W), UNIFORM(0, 12, RANDOM(101)))::NUMBER AS ON_ORDER,
       (FLOOR(i.ON_HAND * UNIFORM(0::FLOAT, 0.5::FLOAT, RANDOM(102))) + IFF(UNIFORM(0::FLOAT, 1::FLOAT, RANDOM(103)) < 0.05, UNIFORM(1, 3, RANDOM(104)), 0))::NUMBER AS ALLOCATED,
       IFF(i.SNAPSHOT_WEEK = latest.W, ROUND(COALESCE(o.TRANSIT_QTY, 0) * dcw.W), UNIFORM(0, 3, RANDOM(105)))::NUMBER AS IN_TRANSIT
FROM BRONZE.INVENTORY_BACKBONE i CROSS JOIN latest
JOIN dcw ON dcw.DC_ID = i.DC_ID
LEFT JOIN on_order o ON o.SKU_ID = i.SKU_ID;

-- ---------------------------------------------------------------- demand forecast: item x DC x month, calibrated to item actuals
CREATE OR REPLACE TABLE BRONZE.DEMAND_FORECAST CLUSTER BY (MONTH, DC_ID) AS
WITH months AS (
  SELECT DISTINCT MONTH FROM BRONZE.CALENDAR WHERE MONTH >= TO_VARCHAR(DATEADD(month, -11, '{{AS_OF}}'::DATE), 'YYYY-MM')
  UNION ALL SELECT TO_VARCHAR(DATEADD(month, k.I, '{{AS_OF}}'::DATE), 'YYYY-MM') FROM (SELECT SEQ4() + 1 AS I FROM TABLE(GENERATOR(ROWCOUNT => 3))) k
), fam_bias AS (
  -- per-family planning bias in +-12%, deterministic (hash of family) and centred so the company total is unbiased
  SELECT FAMILY, B - AVG(B) OVER () AS BIAS
  FROM (SELECT FAMILY, -0.12 + 0.24 * (MOD(ABS(HASH(FAMILY || 'bias')), 1000) / 1000.0) AS B FROM (SELECT DISTINCT FAMILY FROM BRONZE.PRODUCTS_BACKBONE))
), dc AS (
     -- cumulative DC weight (0..1) for an exact proportional split of each SKU-month total
     SELECT DC_ID, WEIGHT / SUM(WEIGHT) OVER () AS W,
            SUM(WEIGHT) OVER (ORDER BY DC_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(WEIGHT) OVER () AS CUM_W
     FROM BRONZE.DISTRIBUTION_CENTERS
), base AS (
     -- history months: forecast is calibrated to the month's actual (family bias +-12%, noise 0.7-1.3), with a
     -- 5% chance of forecasting one unit where nothing sold. Future months (after AS_OF) use last year's actual.
     SELECT p.SKU_ID, p.FAMILY, m.MONTH,
            CASE WHEN m.MONTH > TO_VARCHAR('{{AS_OF}}'::DATE, 'YYYY-MM') THEN COALESCE(a12.UNITS_SOLD, 0)
                 ELSE COALESCE(a.UNITS_SOLD, IFF(MOD(ABS(HASH(p.SKU_ID, m.MONTH)), 100) < 5, 1, 0)) END AS BASE_UNITS
     FROM BRONZE.PRODUCTS_BACKBONE p CROSS JOIN months m
     LEFT JOIN SILVER.ITEM_MONTHLY a ON a.SKU_ID = p.SKU_ID AND a.MONTH = m.MONTH
     LEFT JOIN SILVER.ITEM_MONTHLY a12 ON a12.SKU_ID = p.SKU_ID AND a12.MONTH = TO_VARCHAR(DATEADD(month, -12, TO_DATE(m.MONTH || '-01')), 'YYYY-MM')
   ),
   tot AS (
     SELECT b.SKU_ID, b.FAMILY, b.MONTH,
            GREATEST(0, ROUND(b.BASE_UNITS * (1.0 + fb.BIAS) * (0.7 + UNIFORM(0::FLOAT, 1::FLOAT, RANDOM(112)) * 0.6)))::NUMBER AS T,
            ABS(HASH(b.SKU_ID, b.MONTH)) AS H
     FROM base b JOIN fam_bias fb ON fb.FAMILY = b.FAMILY
   )
-- Split the SKU-month total across DCs by weight without rounding drift: DC_k gets FLOOR(T*CUM_k + r) - FLOOR(T*CUM_{k-1} + r)
-- with a per-SKU-month offset r in [0,1), which telescopes to exactly T over all DCs and rounds without bias.
SELECT t.MONTH, dc.DC_ID, t.SKU_ID,
       (FLOOR(t.T * dc.CUM_W + MOD(t.H, 1000) / 1000.0) - FLOOR(t.T * (dc.CUM_W - dc.W) + MOD(t.H, 1000) / 1000.0))::NUMBER AS FORECAST_UNITS,
       ARRAY_CONSTRUCT('seasonal_naive','ets','croston','override')[MOD(ABS(HASH(t.SKU_ID)), 4)]::VARCHAR AS FORECAST_METHOD
FROM tot t CROSS JOIN dc;

-- ---------------------------------------------------------------- MRP plan (latest run) + work orders
CREATE OR REPLACE TABLE BRONZE.MRP_PLAN CLUSTER BY (RUN_MONTH, EXCEPTION_CODE) AS
WITH run AS (SELECT TO_VARCHAR('{{AS_OF}}'::DATE, 'YYYY-MM') AS RUN_MONTH),
     latest AS (SELECT MAX(SNAPSHOT_WEEK) AS W FROM BRONZE.INVENTORY_SNAPSHOTS),
     snap AS (SELECT s.DC_ID, s.SKU_ID, s.ON_HAND, s.ALLOCATED, s.ON_ORDER, s.IN_TRANSIT FROM BRONZE.INVENTORY_SNAPSHOTS s JOIN latest ON latest.W = s.SNAPSHOT_WEEK),
     fc3 AS (SELECT DC_ID, SKU_ID, SUM(FORECAST_UNITS) AS DEMAND FROM BRONZE.DEMAND_FORECAST f CROSS JOIN run WHERE f.MONTH > run.RUN_MONTH GROUP BY DC_ID, SKU_ID),
     calc AS (
       SELECT run.RUN_MONTH, s.DC_ID, s.SKU_ID, p.SAFETY_STOCK, p.LEAD_BAND,
              COALESCE(f.DEMAND, 0) AS DEMAND,
              (s.ON_HAND - s.ALLOCATED + s.ON_ORDER + s.IN_TRANSIT) AS AVAILABLE,
              (s.ON_HAND - s.ALLOCATED) AS FREE,
              COALESCE(f.DEMAND, 0) + p.SAFETY_STOCK - (s.ON_HAND - s.ALLOCATED + s.ON_ORDER + s.IN_TRANSIT) AS NET_REQ,
              CASE p.LEAD_BAND WHEN 'in_stock' THEN 7 WHEN '2_4_weeks' THEN 21 WHEN '4_8_weeks' THEN 42 ELSE 180 END AS LEAD_DAYS,
              DATEADD(day, UNIFORM(14, 75, RANDOM(121)), '{{AS_OF}}'::DATE) AS DUE,
              UNIFORM(0::FLOAT, 1::FLOAT, RANDOM(122)) AS R
       FROM snap s CROSS JOIN run
       JOIN BRONZE.PRODUCTS_BACKBONE p ON p.SKU_ID = s.SKU_ID
       LEFT JOIN fc3 f ON f.DC_ID = s.DC_ID AND f.SKU_ID = s.SKU_ID
     )
SELECT 'MRP-' || RUN_MONTH || '-' || DC_ID || '-' || SKU_ID AS PLAN_ID, RUN_MONTH, DC_ID, SKU_ID,
       NET_REQ::NUMBER AS NET_REQUIREMENT,
       IFF(NET_REQ > 0, GREATEST(NET_REQ, 5), 0)::NUMBER AS PLANNED_ORDER_QTY,
       IFF(NET_REQ > 0, DATEADD(day, -LEAD_DAYS, DUE), NULL) AS PLANNED_RELEASE_DATE,
       IFF(NET_REQ > 0, DUE, NULL) AS DUE_DATE,
       CASE
         WHEN NET_REQ > 0 AND DATEADD(day, -LEAD_DAYS, DUE) < '{{AS_OF}}'::DATE AND FREE < DEMAND * 0.3 THEN 'shortage'
         WHEN NET_REQ > 0 AND DATEADD(day, -LEAD_DAYS, DUE) < '{{AS_OF}}'::DATE THEN 'expedite'
         WHEN NET_REQ > 0 THEN 'none'
         WHEN AVAILABLE > DEMAND * 3 + SAFETY_STOCK * 2 AND AVAILABLE - FREE > 0 THEN IFF(R < 0.5, 'cancel', 'de_expedite')
         WHEN AVAILABLE > DEMAND * 4 + SAFETY_STOCK * 3 THEN 'excess'
         ELSE 'none' END AS EXCEPTION_CODE
FROM calc;

CREATE OR REPLACE TABLE BRONZE.WORK_ORDERS AS
WITH cand AS (
  SELECT m.*, p.FAMILY, UNIFORM(0::FLOAT, 1::FLOAT, RANDOM(131)) AS R, UNIFORM(-30, 20, RANDOM(132)) AS START_OFF, UNIFORM(7, 28, RANDOM(133)) AS DUR
  FROM BRONZE.MRP_PLAN m JOIN BRONZE.PRODUCTS_BACKBONE p ON p.SKU_ID = m.SKU_ID
  WHERE m.PLANNED_ORDER_QTY > 0 AND p.FAMILY IN ('Lamps','Alabaster','Cordless') AND MOD(ABS(HASH(m.PLAN_ID)), 2) = 0
)
SELECT 'WO-' || DC_ID || '-' || SKU_ID AS WO_ID, SKU_ID, DC_ID, PLANNED_ORDER_QTY AS QTY,
       DATEADD(day, START_OFF, '{{AS_OF}}'::DATE) AS START_DATE,
       DATEADD(day, START_OFF + DUR, '{{AS_OF}}'::DATE) AS DUE_DATE,
       CASE WHEN R < 0.25 THEN IFF(START_OFF < 0, 'released', 'planned') WHEN R < 0.50 THEN 'released' WHEN R < 0.75 THEN 'in_progress' WHEN R < 0.95 THEN 'complete' ELSE 'cancelled' END AS STATUS
FROM cand;

-- ---------------------------------------------------------------- GOLD aggregates (small; what the app reads on Snowflake for heavy metrics)
CREATE OR REPLACE TABLE GOLD.CHANNEL_FAMILY AS
SELECT DEALER_ID, CHANNEL, REGION, FAMILY, SUM(UNITS_SOLD) AS UNITS_SOLD, SUM(NET_SALES_CENTS)/100.0 AS NET_SALES,
       SUM(MARGIN_CENTS)/100.0 AS MARGIN, SUM(ON_HAND) AS ON_HAND
FROM SILVER.FACTS GROUP BY DEALER_ID, CHANNEL, REGION, FAMILY;

CREATE OR REPLACE TABLE GOLD.CHANNEL_FAMILY_ALL AS
SELECT DEALER_ID, CHANNEL, REGION, FAMILY, SUM(UNITS_SOLD) AS UNITS_SOLD, SUM(NET_SALES_CENTS)/100.0 AS NET_SALES, SUM(MARGIN_CENTS)/100.0 AS MARGIN
FROM GOLD.MONTHLY_BASE WHERE MONTH >= TO_VARCHAR(DATEADD(month, -11, '{{AS_OF}}'::DATE), 'YYYY-MM')
GROUP BY DEALER_ID, CHANNEL, REGION, FAMILY;

CREATE OR REPLACE TABLE GOLD.INVENTORY_WEEKLY_DC AS
SELECT SNAPSHOT_WEEK, DC_ID, SUM(ON_HAND) AS ON_HAND, SUM(ON_ORDER) AS ON_ORDER, SUM(ALLOCATED) AS ALLOCATED, SUM(IN_TRANSIT) AS IN_TRANSIT,
       COUNT(*) AS SKUS, SUM(IFF(ON_HAND - ALLOCATED < 0, 1, 0)) AS OVERSOLD_SKUS, SUM(IFF(ON_HAND = 0, 1, 0)) AS STOCKOUT_SKUS
FROM BRONZE.INVENTORY_SNAPSHOTS GROUP BY SNAPSHOT_WEEK, DC_ID;

CREATE OR REPLACE TABLE GOLD.FORECAST_FAMILY_MONTH AS
SELECT p.FAMILY, f.MONTH, SUM(f.FORECAST_UNITS) AS FORECAST_UNITS
FROM BRONZE.DEMAND_FORECAST f JOIN BRONZE.PRODUCTS_BACKBONE p ON p.SKU_ID = f.SKU_ID GROUP BY p.FAMILY, f.MONTH;

CREATE OR REPLACE TABLE GOLD.MRP_EXCEPTION_SUMMARY AS
SELECT RUN_MONTH, DC_ID, EXCEPTION_CODE, COUNT(*) AS SKUS, SUM(PLANNED_ORDER_QTY) AS PLANNED_UNITS, SUM(NET_REQUIREMENT) AS NET_REQUIREMENT
FROM BRONZE.MRP_PLAN GROUP BY RUN_MONTH, DC_ID, EXCEPTION_CODE;

CREATE OR REPLACE TABLE GOLD.VENDOR_SCORECARD AS
WITH v_margin AS (
  SELECT p.VENDOR_ID, ROUND(100.0 * SUM(sf.MARGIN_CENTS) / NULLIF(SUM(sf.NET_SALES_CENTS), 0), 1) AS MARGIN_PCT
  FROM SILVER.FACTS sf JOIN BRONZE.PRODUCTS p ON p.SKU_ID = sf.SKU_ID GROUP BY p.VENDOR_ID
)
SELECT v.VENDOR_ID, v.NAME, v.COUNTRY, vk.OTIF_PCT, ROUND(100.0 - vk.DEFECT_PCT, 1) AS QUALITY_PCT,
       ROUND(100.0 * LEAST(1.0, vk.PROMISED_LEAD_DAYS / NULLIF(vk.AVG_LEAD_DAYS, 0)), 1) AS LEAD_RELIABILITY,
       COALESCE(vm.MARGIN_PCT, 0) AS MARGIN_PCT,
       ROUND(0.35 * vk.OTIF_PCT + 0.25 * (100.0 - vk.DEFECT_PCT) + 0.20 * (100.0 * LEAST(1.0, vk.PROMISED_LEAD_DAYS / NULLIF(vk.AVG_LEAD_DAYS, 0))) + 0.20 * COALESCE(vm.MARGIN_PCT, 0), 1) AS SCORE
FROM SILVER.VENDOR_KPI vk JOIN BRONZE.VENDORS v ON v.VENDOR_ID = vk.VENDOR_ID LEFT JOIN v_margin vm ON vm.VENDOR_ID = v.VENDOR_ID;

-- ---------------------------------------------------------------- SERVING (names + lowercase-compatible columns match the SQLite contract)
CREATE OR REPLACE SECURE VIEW SERVING.SILVER_FACTS AS SELECT * FROM SILVER.FACTS;
CREATE OR REPLACE SECURE VIEW SERVING.SILVER_MONTHLY AS SELECT * FROM SILVER.MONTHLY;
CREATE OR REPLACE SECURE VIEW SERVING.SILVER_VENDOR_KPI AS SELECT * FROM SILVER.VENDOR_KPI;
CREATE OR REPLACE SECURE VIEW SERVING.DEALERS AS SELECT DEALER_ID, NAME, REGION, CHANNEL_FOCUS, CITY, TERRITORY_ID FROM BRONZE.DEALERS;
CREATE OR REPLACE SECURE VIEW SERVING.PRODUCTS AS SELECT SKU_ID, NAME, FAMILY, DESIGNER, FINISH, LIST_PRICE_CENTS, LEAD_BAND, COST_CENTS, VENDOR_ID, SAFETY_STOCK FROM BRONZE.PRODUCTS;
CREATE OR REPLACE SECURE VIEW SERVING.TERRITORIES AS SELECT * FROM BRONZE.TERRITORIES;
CREATE OR REPLACE SECURE VIEW SERVING.SALESPEOPLE AS SELECT * FROM BRONZE.SALESPEOPLE;
CREATE OR REPLACE SECURE VIEW SERVING.VENDORS AS SELECT * FROM BRONZE.VENDORS;
CREATE OR REPLACE SECURE VIEW SERVING.QUARANTINE AS SELECT * FROM SILVER.QUARANTINE;
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_CHANNEL_FAMILY AS SELECT * FROM GOLD.CHANNEL_FAMILY;
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_CHANNEL_FAMILY_ALL AS SELECT * FROM GOLD.CHANNEL_FAMILY_ALL;
CREATE OR REPLACE SECURE VIEW SERVING.DISTRIBUTION_CENTERS AS SELECT DC_ID, NAME, REGION, STATE FROM BRONZE.DISTRIBUTION_CENTERS;
-- Snowflake-only (calibration tiers), not part of the SQLite contract.
CREATE OR REPLACE SECURE VIEW SERVING.DEALER_TIERS AS SELECT DEALER_ID, TIER FROM BRONZE.DEALER_TIER;
CREATE OR REPLACE SECURE VIEW SERVING.REP_ASSIGNMENTS AS SELECT REP_ID, DEALER_ID, START_MONTH, END_MONTH FROM BRONZE.REP_ASSIGNMENTS;
CREATE OR REPLACE SECURE VIEW SERVING.REP_QUOTAS AS SELECT REP_ID, QUARTER, QUOTA_CENTS FROM BRONZE.REP_QUOTAS;
CREATE OR REPLACE SECURE VIEW SERVING.VENDOR_CONTRACTS AS SELECT * FROM BRONZE.VENDOR_CONTRACTS;
CREATE OR REPLACE SECURE VIEW SERVING.COMPONENTS AS SELECT * FROM BRONZE.COMPONENTS;
CREATE OR REPLACE SECURE VIEW SERVING.BOM AS SELECT SKU_ID AS PARENT_SKU_ID, COMPONENT_ID, QTY_PER FROM BRONZE.BOM;
CREATE OR REPLACE SECURE VIEW SERVING.PURCHASE_ORDERS AS
  SELECT PO_ID, VENDOR_ID, DC_ID, TO_VARCHAR(ORDER_DATE, 'YYYY-MM-DD') AS ORDER_DATE, TO_VARCHAR(PROMISED_DATE, 'YYYY-MM-DD') AS PROMISED_DATE, STATUS FROM BRONZE.PURCHASE_ORDERS;
CREATE OR REPLACE SECURE VIEW SERVING.PO_LINES AS
  SELECT PO_ID, LINE_NO, SKU_ID, QTY_ORDERED, UNIT_COST_CENTS, QTY_RECEIVED, TO_VARCHAR(PROMISED_DATE, 'YYYY-MM-DD') AS PROMISED_DATE FROM BRONZE.PO_LINES;
CREATE OR REPLACE SECURE VIEW SERVING.SHIPMENTS AS
  SELECT SHIPMENT_ID, PO_ID, VENDOR_ID, DC_ID, TO_VARCHAR(SHIP_DATE, 'YYYY-MM-DD') AS SHIP_DATE, TO_VARCHAR(ETA_DATE, 'YYYY-MM-DD') AS ETA_DATE,
         TO_VARCHAR(ARRIVAL_DATE, 'YYYY-MM-DD') AS ARRIVAL_DATE, MODE, FREIGHT_CENTS, CARTONS FROM BRONZE.SHIPMENTS;
CREATE OR REPLACE SECURE VIEW SERVING.RECEIPTS AS
  SELECT RECEIPT_ID, SHIPMENT_ID, PO_ID, LINE_NO, SKU_ID, QTY_RECEIVED, QTY_DEFECTIVE, TO_VARCHAR(RECEIVED_DATE, 'YYYY-MM-DD') AS RECEIVED_DATE FROM BRONZE.RECEIPTS;
CREATE OR REPLACE SECURE VIEW SERVING.INVENTORY_SNAPSHOTS AS SELECT * FROM BRONZE.INVENTORY_SNAPSHOTS;
CREATE OR REPLACE SECURE VIEW SERVING.DEMAND_FORECAST AS SELECT * FROM BRONZE.DEMAND_FORECAST;
CREATE OR REPLACE SECURE VIEW SERVING.MRP_PLAN AS
  SELECT PLAN_ID, RUN_MONTH, DC_ID, SKU_ID, NET_REQUIREMENT, PLANNED_ORDER_QTY, TO_VARCHAR(PLANNED_RELEASE_DATE, 'YYYY-MM-DD') AS PLANNED_RELEASE_DATE,
         TO_VARCHAR(DUE_DATE, 'YYYY-MM-DD') AS DUE_DATE, EXCEPTION_CODE FROM BRONZE.MRP_PLAN;
CREATE OR REPLACE SECURE VIEW SERVING.WORK_ORDERS AS
  SELECT WO_ID, SKU_ID, DC_ID, QTY, TO_VARCHAR(START_DATE, 'YYYY-MM-DD') AS START_DATE, TO_VARCHAR(DUE_DATE, 'YYYY-MM-DD') AS DUE_DATE, STATUS FROM BRONZE.WORK_ORDERS;
-- Gold-backed serving views used by the app's Snowflake dialect for heavy metrics.
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_INVENTORY_WEEKLY_DC AS SELECT * FROM GOLD.INVENTORY_WEEKLY_DC;
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_FORECAST_FAMILY_MONTH AS SELECT * FROM GOLD.FORECAST_FAMILY_MONTH;
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_MRP_EXCEPTION_SUMMARY AS SELECT * FROM GOLD.MRP_EXCEPTION_SUMMARY;
CREATE OR REPLACE SECURE VIEW SERVING.GOLD_VENDOR_SCORECARD AS SELECT * FROM GOLD.VENDOR_SCORECARD;
CREATE OR REPLACE VIEW SERVING.RUNS AS SELECT NULL::VARCHAR RUN_ID,NULL::VARCHAR FINISHED_AT,0::NUMBER ACCEPTED,0::NUMBER DUPLICATES,0::NUMBER QUARANTINED,0::NUMBER CURRENT_FACTS,0::FLOAT DURATION_MS WHERE FALSE;

SELECT 'silver_facts' AS K, COUNT(*) AS N FROM SILVER.FACTS
UNION ALL SELECT 'silver_monthly', COUNT(*) FROM SILVER.MONTHLY
UNION ALL SELECT 'silver_quarantine', COUNT(*) FROM SILVER.QUARANTINE
UNION ALL SELECT 'item_monthly', COUNT(*) FROM SILVER.ITEM_MONTHLY
UNION ALL SELECT 'inventory_snapshots', COUNT(*) FROM BRONZE.INVENTORY_SNAPSHOTS
UNION ALL SELECT 'demand_forecast', COUNT(*) FROM BRONZE.DEMAND_FORECAST
UNION ALL SELECT 'mrp_plan', COUNT(*) FROM BRONZE.MRP_PLAN
UNION ALL SELECT 'work_orders', COUNT(*) FROM BRONZE.WORK_ORDERS
UNION ALL SELECT 'rep_quotas', COUNT(*) FROM BRONZE.REP_QUOTAS
UNION ALL SELECT 'vendor_kpi', COUNT(*) FROM SILVER.VENDOR_KPI;
